### ISSUE TITLE
File path longer 254 symbol

### ISSUE THREAD

**Issue by Teriand** [Microsoft/team-explorer-everywhere#182]
system:
SMP Debian 3.2.84-1 x86_64 GNU/Linux
TEE-CLC-14.114.0

tf get with long path give error:

Local path /var/opengrok/repository/TeamWork/../dbo.CONFLICT_RESOLUTION_RULES.sql is too long.  The item will not be retrieved

Can be reset MAX_PATH from 254 ?

**Comment by jpricketMSFT** [comment]
@Teriand - What version is your TFS server? Originally, the TFS server limited the path length to 260 characters. It was then changed in 2012 (I think) to 400 characters. But since the database stores the path in limited fields for faster query performance, you cannot store arbitrarily long paths in the server. The clients may still restrict the local paths to 260 characters to make sure the paths fit on the server. Have you tried moving your workspace to a shorter path (/home/user/w or even /opt/w) ?
Thanks,
Jason

**Comment by Teriand** [comment]
Visual Studio Team Foundation Server 2015

If this is a server restriction, i close it.

**Comment by jpricketMSFT** [comment]
The server is definitely limited to 400 characters in the path fields. However, I am not sure if any 260 limits are still enforced. In general with TFVC, you have to keep the workspaces in as short a path as possible. I don't think there is much you can do to change the limit.
