### ISSUE TITLE
tf command doesn't seem to work with OpenJ9

### ISSUE THREAD

**Issue by dgtlrift** [microsoft/team-explorer-everywhere#308]
tf help or any parameter doesn't seem to work when using OpenJ9 virtual machine (to avoid licensing issues of Oracle Java)

**Comment by ForNeVeR** [comment]
Please take a look at https://github.com/microsoft/team-explorer-everywhere/pull/251 and https://github.com/microsoft/team-explorer-everywhere/issues/289#issuecomment-530436692

Probably it'll work if you define an environment variable `TF_NOTELEMETRY=TRUE`. The reason is `java.xml.bind` that was modularized and now require an explicit `--add-modules` argument, but it's probably easier to shut the offending functionality off completely.

**Comment by dgtlrift** [comment]
Adding TF_NOTELEMETRY=TRUE from #289 [comment ](https://github.com/microsoft/team-explorer-everywhere/issues/289#issuecomment-530436692) seems to the script seems to have resolved the issue - not sure of the significance of this environment variable.

**Comment by ForNeVeR** [comment]
Look: Java 9+ is modularized, so it requires an additional option to enable the `java.xml.bind` module to be used, and I think that this module was removed from JDK in some future version (12 or 13, can't remember right now).

Fortunately, the only code (detected so far) that uses that module in the whole Team Explorer Everywhere Command Line Client code base is the one that sends the telemetry. So, by disabling the telemetry, you disable the usage of this module, and the client works.

This variable is significant :)

**Comment by brunoborges** [comment]
The dependency (JAR) for XML can be downloaded and shipped with the tool, and set in the classpath as usual. No need to use modules.

**Comment by eric-milles** [comment]
This is fixed in 14.135.0
