### ISSUE TITLE
Web-Service Generator Source Code

### ISSUE THREAD

**Issue by wjk** [Microsoft/team-explorer-everywhere#60]
I was browsing some of the generated source files in the `com.microsoft.tfs.code.ws` library, and noticed that the file headers state that [they were created by `com.microsoft.tfs.core.ws.generator.Generator`](https://github.com/Microsoft/team-explorer-everywhere/blob/master/source/com.microsoft.tfs.core.ws/generated-src/ms/tfs/services/authorization/_03/_ApplicationGroupProperty.java#L4-L7). This code is not, and as far as I know never has been, released. Is there any reason why? I am not as interested in the generator itself as the source files used as input to the generator, as I want to create a TFS client library for a Mac app I am working on, and need to generate code in Swift. Thanks!

**Comment by jpricketMSFT** [comment]
No, we have not released the generator code. The inputs are simply the server end points themselves. The source code for the VSTS end points has not been released either. Perhaps you can convert the Java code to Swift or just use the Java libraries from your Swift code (I haven't done any Swift, so I don't know what's possible).

Good Luck,
Jason

**Comment by sterwill** [comment]
@wjk The original generator was written in Java.  It used an open source library to parse TFS's WSDL (wsdl4j?) and Apache Velocity to generate the Java class files (that was a lot of work).  We wrote our own because we supported Java 4 at the time, and all of the suitable existing SOAP client runtimes and code generators required Java 5 or newer.

Today you could use any SOAP client runtime for Swift to get the job done.

(I wrote the original TEE generator and SOAP runtime a long time ago and maintained it for a while at Microsoft)
